{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: bruiser-gateway
spec:
  selector:
    matchLabels:
      app: bruiser-gateway
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
{{- end }}
